# Generated by Django 4.1.1 on 2022-09-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='InformacionSalud',
        ),
    ]
